prj_Practice_NorthWind/prj_Practice_NorthWind/Models/Employee.cs
namespace prj_Practice_NorthWind.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Employee")]
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            EmployeeInformation = new HashSet<EmployeeInformation>();
        }

        public int EmployeeID { get; set; }

        [Required]
        [StringLength(20)]
        public string LastName { get; set; }

        [Required]
        [StringLength(10)]
        public string FirstName { get; set; }

        [StringLength(30)]
        public string Title { get; set; }

        [StringLength(25)]
        public string TitleOfCourtesy { get; set; }

        public DateTime? BirthDate { get; set; }

        public DateTime? HireDate { get; set; }

        [StringLength(60)]
        public string Address { get; set; }

        [StringLength(15)]
        public string City { get; set; }

        [StringLength(15)]
        public string Region { get; set; }

        [StringLength(10)]
        public string PostalCode { get; set; }

        [StringLength(15)]
        public string Country { get; set; }

        [StringLength(24)]
        public string HomePhone { get; set; }

        [StringLength(4)]
        public string Extension { get; set; }

        [Column(TypeName = "image")]
        public byte[] Photo { get; set; }

        [Column(TypeName = "ntext")]
        public string Notes { get; set; }

        public int? ReportsTo { get; set; }

        [StringLength(255)]
        public string PhotoPath { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInformation> EmployeeInformation { get; set; }
        [NotMapped]
        public List<string> EmployeeCheckboxLabel { get; internal set; }
        [NotMapped]
        public EmployeeEntity MyCheckBox { get; internal set; }

    }
}

prj_Practice_NorthWind/prj_Practice_NorthWind/Models/Employees.cs
namespace prj_Practice_NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            Employees1 = new HashSet<Employees>();
            Orders = new HashSet<Orders>();
            Territories = new HashSet<Territories>();
        }

        [Key]
        public int EmployeeID { get; set; }

        [StringLength(20)]
        public string LastName { get; set; }

        [StringLength(10)]
        public string FirstName { get; set; }

        [StringLength(30)]
        public string Title { get; set; }

        [StringLength(25)]
        public string TitleOfCourtesy { get; set; }

        public DateTime? BirthDate { get; set; }

        public DateTime? HireDate { get; set; }

        [StringLength(60)]
        public string Address { get; set; }

        [StringLength(15)]
        public string City { get; set; }

        [StringLength(15)]
        public string Region { get; set; }

        [StringLength(10)]
        public string PostalCode { get; set; }

        [StringLength(15)]
        public string Country { get; set; }

        [StringLength(24)]
        public string HomePhone { get; set; }

        [StringLength(4)]
        public string Extension { get; set; }

        [Column(TypeName = "image")]
        public byte[] Photo { get; set; }

        [Column(TypeName = "ntext")]
        public string Notes { get; set; }

        public int? ReportsTo { get; set; }

        [StringLength(255)]
        public string PhotoPath { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees1 { get; set; }

        public virtual Employees Employees2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territories> Territories { get; set; }
    }
}

prj_Practice_NorthWind/prj_Practice_NorthWind/Controllers/NorthwindController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prj_Practice_NorthWind.Models;
using Xceed.Document.NET;
using Xceed.Words.NET;

namespace prj_Practice_NorthWind.Controllers
{
    public class NorthwindController : Controller
    {
        public Northwind _db = new Northwind();
        // GET: Northwind
        public ActionResult IndexJoin()
        {
            var result = from od in _db.Order_Details
                         join o in _db.Orders on od.OrderID equals o.OrderID into odo
                         from o in odo.DefaultIfEmpty()
                         select new OrderDetails_OrdersViewModel { Order = o, OrderDetails = od };
            return View(result);
        }
        public ActionResult IndexVM()
        {
            List<Order_OrederDetialsListViewModel> result = new List<Order_OrederDetialsListViewModel>();
            // 一(第一層)對多
            foreach (var o in _db.Orders)
            {
                //會有好幾筆Order_Details
                List<Order_Details> od = new List<Order_Details>();
                foreach (var item in _db.Order_Details.Where(x => x.OrderID == o.OrderID))
                {
                    od.Add(item);
                }

                result.Add(new Order_OrederDetialsListViewModel { order = o, order_details = od });

            }

            // DrowDownList
            var selectList = new List<SelectListItem>()
            {
                new SelectListItem {Text="text-1", Value="value-1" },
                new SelectListItem {Text="text-2", Value="value-2" },
                new SelectListItem {Text="text-3", Value="value-3" },
            };

            //預設選擇哪一筆
            selectList.Where(q => q.Value == "value-2").First().Selected = true;

            ViewBag.SelectList = selectList;

            return View(result.ToList());
        }
        public ActionResult EmployeeIndex()
        {
            var Employee = _db.Employee;
            return View(Employee);
        }
        public ActionResult EmployeeCreate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmployeeCreate(Employee employeesData)
        {
            if (employeesData == null)
            {   // 沒有輸入內容，就會報錯 - Bad Request
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                _db.Employee.Add(employeesData);
                _db.SaveChanges();
                return RedirectToAction("EmployeeIndex");
            }
            else
            {
                ModelState.AddModelError("Value1", " 自訂錯誤訊息(1) ");
                ModelState.AddModelError("Value2", " 自訂錯誤訊息(2) ");
                return View();
            }
        }
        public ActionResult EmployeeEdit(int id)
        {
            if (id == 0)
            {
                Employee employeesData = new Employee();
                return View(employeesData);
            }
            else
            {
                Employee employeesData = _db.Employee.Find(id);
                return View(employeesData);
            }

        }
        public ActionResult EmployeeView(int id)
        {
            if (id == 0)
            {
                Employee employeesData = new Employee();
                return View(employeesData);
            }
            else
            {
                Employee employeesData = _db.Employee.Find(id);
                ViewBag.employeesInfoData = _db.EmployeeInformation.Where(x => x.EmployeeID == id).ToList();
                return View(employeesData);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmployeeEdit(Employee employeesData)
        {
            if (employeesData == null)
            {   // 沒有輸入內容，就會報錯 - Bad Request
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                Employee employees = _db.Employee.Find(employeesData.EmployeeID);

                employees.FirstName = employeesData.FirstName;
                employees.LastName = employeesData.LastName;
                employees.Address = employeesData.Address;
                employees.City = employeesData.City;
                employees.HomePhone = employeesData.HomePhone;
                employees.BirthDate = employeesData.BirthDate;
                employees.PostalCode = employeesData.PostalCode;

                _db.SaveChanges();
                return RedirectToAction("EmployeeIndex");
            }
            else
            {
                ModelState.AddModelError("Value1", " 自訂錯誤訊息(1) ");
                ModelState.AddModelError("Value2", " 自訂錯誤訊息(2) ");
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmployeeDelete(int id)
        {
            if (ModelState.IsValid)
            {
                Employee DeleteItem = _db.Employee.Find(id);
                _db.Employee.Remove(DeleteItem);
                _db.SaveChanges();
                return RedirectToAction("EmployeeIndex");
            }
            else
            {
                ModelState.AddModelError("Value1", " 自訂錯誤訊息(1) ");
                ModelState.AddModelError("Value2", " 自訂錯誤訊息(2) ");
                return View();
            }

        }

        [HttpPost]
        public JsonResult GetServiceQuote(int id = 0)
        {
            Employee vm = new Employee();
            var data = _db.Employee;
            var model = _db.Employee.Where(x => x.EmployeeID == id).FirstOrDefault();
            if (model.EmployeeID != null)
            {
                vm.LastName = model.LastName;
                vm.FirstName = model.FirstName;
                vm.Address = model.Address;
                vm.City = model.City;
            }

            var EmployeeCheckboxLabel = new List<string>();
            if (id == 5)
            {
                EmployeeCheckboxLabel.Add("陸軍");
                EmployeeCheckboxLabel.Add("海軍");
                EmployeeCheckboxLabel.Add("空軍");
                EmployeeCheckboxLabel.Add("陸戰隊");
            }
            if (id == 6)
            {
                EmployeeCheckboxLabel.Add("陸軍");
                EmployeeCheckboxLabel.Add("海軍");
            }
            if (id == 7)
            {
                EmployeeCheckboxLabel.Add("陸軍");
            }
            vm.EmployeeCheckboxLabel = EmployeeCheckboxLabel;

            //==============================================================================================================
            var EmployeeCheckbox = new List<MyListItem>();
            if (id == 5)
            {
                EmployeeCheckbox.Add(new MyListItem { Checkboxid = 1, CheckboxName = "測試1", IsChecked = false });
                EmployeeCheckbox.Add(new MyListItem { Checkboxid = 2, CheckboxName = "測試2", IsChecked = false });
                EmployeeCheckbox.Add(new MyListItem { Checkboxid = 3, CheckboxName = "測試3", IsChecked = false });
            }
            else if (id == 6)
            {
                EmployeeCheckbox.Add(new MyListItem { Checkboxid = 1, CheckboxName = "測試1", IsChecked = false });
                EmployeeCheckbox.Add(new MyListItem { Checkboxid = 2, CheckboxName = "測試2", IsChecked = false });
            }
            else if (id == 7)
            {
                EmployeeCheckbox.Add(new MyListItem { Checkboxid = 1, CheckboxName = "測試1", IsChecked = false });
            }

            EmployeeEntity res = new EmployeeEntity { EmplyeeCheckbox = EmployeeCheckbox };
            vm.MyCheckBox = res;

            return Json(vm, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ExportWord()
        {
            string fileName = @"G:\prj_practice\prj_Practice_NorthWind\prj_Practice_NorthWind\WordTemplate\employeeTemplate.docx";
            string handle = Guid.NewGuid().ToString();
            List<Employee> EmployeeList = _db.Employee.ToList();
            using (DocX document = DocX.Load(fileName))
            {
                int i = 0;
                int j = 0;
                foreach (var Employee in EmployeeList)
                {
                    Table tb = document.AddTable(2, 4);
                    tb.Design = TableDesign.LightGridAccent5;//套上的表格格式
                    tb.Alignment = Alignment.center;//至中格式
                    // Title
                    tb.Rows[0].Cells[0].Paragraphs[0].Append("LastName");
                    tb.Rows[1].Cells[0].Paragraphs[0].Append("FirstName");
                    tb.Rows[0].Cells[2].Paragraphs[0].Append("Address");
                    tb.Rows[1].Cells[2].Paragraphs[0].Append("City");

                    // Value
                    tb.Rows[0].Cells[1].Paragraphs[0].Append(Employee.LastName);
                    tb.Rows[1].Cells[1].Paragraphs[0].Append(Employee.FirstName);
                    tb.Rows[0].Cells[3].Paragraphs[0].Append(Employee.Address);
                    tb.Rows[1].Cells[3].Paragraphs[0].Append(Employee.City);
                    var row = tb.InsertRow();//新增列
                    i++;
                    j++;

                    // var pa = document.InsertParagraph(Employee.EmployeeID.ToString());
                    document.InsertTable(tb);
                    //var pa = document.InsertParagraph("插入一個新段落");
                    //pa.InsertTableAfterSelf(tb);
                }


                if (Directory.Exists($"~/WordTemplate/{handle}/{fileName}"))
                {
                    //資料夾存在
                    string fileNamexx = @"G:\prj_practice\prj_Practice_NorthWind\prj_Practice_NorthWind\WordTemplate\" + handle + @"\employeeTemplate_Result" + ".docx";
                    document.SaveAs(fileNamexx);

prj_Practice_NorthWind/prj_Practice_NorthWind/Views/Northwind/EmployeeCreate.cshtml
@model prj_Practice_NorthWind.Models.Employee

@{
    ViewBag.Title = "EmployeeCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EmployeeCreate</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "EmployeeIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prj_Practice_NorthWind/prj_Practice_NorthWind/Views/Northwind/EmployeeEdit.cshtml
@model prj_Practice_NorthWind.Models.Employee

@{
    ViewBag.Title = "EmployeeEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EmployeeEdit</h2>


@using (@Html.BeginForm("EmployeeEdit", "Northwind", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Employees</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prj_Practice_NorthWind/prj_Practice_NorthWind/Views/Northwind/EmployeeIndex.cshtml
@model IEnumerable<prj_Practice_NorthWind.Models.Employee>

@{
    ViewBag.Title = "EmployeeIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EmployeeIndex</h2>

<p>
    @Html.ActionLink("Create New", "EmployeeCreate")
</p>
<p>
    <button class="btn-primary" id="exportBtn">ExportWord</button>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Address)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.City)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.PostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.HomePhone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomePhone)
            </td>
            <td class="form-inline">
                @Html.ActionLink("Edit", "EmployeeEdit", new { id = item.EmployeeID }) | @Html.ActionLink("View", "EmployeeView", new { id = item.EmployeeID })
                <button type="button" class="btn-primary edit-modal" data-target="#newEmployeeModal" data-obj="@item.EmployeeID">EditModal</button>
                @*@Html.ActionLink("Details", "NorthwindController", new { id = item.EmployeeID })*@

                @using (@Html.BeginForm("EmployeeDelete", "Northwind", FormMethod.Post, new { @class = "Delete", id = item.EmployeeID }))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.EmployeeID)
                    <input type="submit" value="刪除" class="btn" />
                }
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="newEmployeeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Address</h4>
            </div>
            <div class="modal-body">
                <h2>Employee</h2>
                <div>
                    <label>LastName</label>
                    <input id="LastNameId" type="text" readonly="readonly" />
                </div>
                <div>
                    <label>FirstName</label>
                    <input id="FirstNameName" type="text" readonly="readonly" />
                </div>
                <div>
                    <label>Address</label>
                    <input id="AddressName" type="text" readonly="readonly" />
                </div>
                <div>
                    <label>City</label>
                    <input id="CityName" type="text" readonly="readonly" />
                </div>
                <div class="CheckBoxLabel">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="add" type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            $('.edit-modal').click(function () {
                var quoteid = $(this).attr("data-obj");

                $.ajax({
                    type: "POST",
                    url: '/Northwind/GetServiceQuote',
                    data: { "id": quoteid },
                    datatype: "json",
                    success: function (data) {
                        var listHtml = '';
                        var listHtmlLabel = '';
                        var resHTNL = '';
                        var reslabel = data.EmployeeCheckboxLabel;
                        var res = data.MyCheckBox.EmplyeeCheckbox;
                        var cnam = data;

                        //alert(data.CustomerName);
                        //$('#ServiceVM_CustomerName').val(data.CustomerName);
                        $('#LastNameId').val(cnam.LastName);
                        $('#FirstNameName').val(cnam.FirstName);
                        $('#AddressName').val(cnam.Address);
                        $('#CityName').val(cnam.City);
                        $.each(reslabel, function (i) {
                            if (reslabel[i] != "") {
                                listHtmlLabel = " <label id='checkbox" + i + "'>" + reslabel[i] + "</label>";
                                $.each(res, function (t) {
                                    if (res[t].CheckboxName != "") {
                                        listHtml += " <input type='checkbox' " + " name='" + res[t].CheckboxName + "' id='" + res[t].Checkboxid + "' value='" + res[t].Checkboxid + "'>" + res[t].CheckboxName;
                                    }
                                });
                                resHTNL += listHtmlLabel + listHtml;
                                //var resHTNL = listHtmlLabel + listHtml;
                            }


                            //$('#checkbox' + i).append(listHtml);
                        });
                        $(".CheckBoxLabel").html(resHTNL);

                        //$.each(res, function (i) {
                        //    if (res[i].CheckboxName != "") {
                        //        listHtml += " <input type='checkbox' " + " name='" + res[i].CheckboxName + "' id='" + res[i].Checkboxid + "' value='" + res[i].Checkboxid + "'>" + res[i].CheckboxName;
                        //    }
                        //    $('#CheckBox').html(listHtml);
                        //});


                        //$("#ServiceVM_MachineState").innerHTML(data.MachineState);
                        //document.getElementsByName("ServiceVM_MachineZip").value = data.MachineZip;
                        //$('#modalInnerSQ').modal('show');
                        $('#newEmployeeModal').modal();
                    }
                });


            });

            $('#exportBtn').click(exportWord);

            function exportWord() {
                $.ajax({
                    type: "POST",
                    url: '/Northwind/ExportWord',
                    // data: { "id": quoteid },
                    datatype: "json",
                    success: function (data) {
                        //var response = JSON.parse(data);
                        window.location = '/Northwind/Download?fileGuid=' + data.FileGuid
                            + '&filename=' + data.FileName;
                        //window.open('/Northwind/Download?fileGuid=' + data.FileGuid +'&filename=' + data.FileName);
                    }
                })
            }

        });

        $('form.Delete').submit(function () {
            var msg = "您真的確定要刪除嗎？\n\n請確認！"
            if (confirm(msg) == false) {
                return false;
            }
        });

    </script>
}